const products = [
    {
      id: 1,
      name: "Item 1",
      description: "Description of 1'th item",
      img: "/images/image-1.png",
      price: 10.0,
      amount: 1,
    },
    {
      id: 2,
      name: "Item 2",
      description: "Description of 2'nd item",
      img: "/images/image-2.png",
      price: 15.0,
      amount: 1,
    },
    {
      id: 3,
      name: "Item 3",
      description: "Description of 3'rd item",
      img: "/images/image-3.png",
      price: 20.0,
      amount: 1,
    },
    {
      id: 4,
      name: "Item 4",
      description: "Description of 4'th item",
      img: "/images/image-4.png",
      price: 25.0,
      amount: 1,
    },
    {
      id: 5,
      name: "Item 5",
      description: "Description of 5'th item",
      img: "/images/image-1.png",
      price: 10.0,
      amount: 1,
    },
    {
      id: 6,
      name: "Item 6",
      description: "Description of 6'nd item",
      img: "/images/image-2.png",
      price: 15.0,
      amount: 1,
    },
    {
      id: 7,
      name: "Item 7",
      description: "Description of 7'rd item",
      img: "/images/image-3.png",
      price: 20.0,
      amount: 1,
    },
    {
      id: 8,
      name: "Item 8",
      description: "Description of 8'th item",
      img: "/images/image-4.png",
      price: 25.0,
      amount: 1,
    },
  ];
  
  export default products